version: "3.8"
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SQLSxrvxr123#
    volumes:
      - ./sqldata:/var/opt/mssql

  webapp:
    container_name: applicationweb
    image: sk1es/paysol:latest
    domainname: davidh-contacts
    environment:
      - CONNECTION_STRING=Server=sqlserver,1433; Database=SoftUni-Fest; User Id=sa; Password=SQLSxrvxr123#; TrustServerCertificate=True;
    ports: 
      - "5102:80"
    restart: always

volumes:
  sqldata:
    driver: local
